"""exercise info fields, drop log goal

Revision ID: 676a575cbae2
Revises: bd46f554e0dc
Create Date: 2026-07-27 21:23:48.836106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676a575cbae2'
down_revision: Union[str, Sequence[str], None] = 'bd46f554e0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The per-day "goal" field was dropped: it duplicated the notes field in
    # practice and added friction while logging.
    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.drop_column('goal')

    # server_default='' so the columns can be added to existing seeded rows.
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('target_muscles', sa.Text(), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('target_muscles_image_url', sa.String(length=1024), nullable=False,
                      server_default='')
        )
        batch_op.add_column(
            sa.Column('execution', sa.Text(), nullable=False, server_default='')
        )
        batch_op.add_column(
            sa.Column('execution_image_url', sa.String(length=1024), nullable=False,
                      server_default='')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('execution_image_url')
        batch_op.drop_column('execution')
        batch_op.drop_column('target_muscles_image_url')
        batch_op.drop_column('target_muscles')

    with op.batch_alter_table('exercise_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal', sa.TEXT(), nullable=False, server_default=''))

    # ### end Alembic commands ###
