"""add roles and login allowlist

Revision ID: 952f020d89e3
Revises: 4011ba52b378
Create Date: 2026-07-27 17:55:10.849509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952f020d89e3'
down_revision: Union[str, Sequence[str], None] = '4011ba52b378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole', native_enum=False, length=16), server_default='user', nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allowed_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_emails_email'), ['email'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'user', name='userrole', native_enum=False, length=16), server_default='user', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('allowed_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_emails_email'))

    op.drop_table('allowed_emails')
    # ### end Alembic commands ###
