"""name existing unique constraints

The metadata now uses a naming convention (see app/database.py) so SQLite batch
migrations keep working; this renames the constraints created unnamed earlier.

Original message: drift check

Revision ID: bd46f554e0dc
Revises: 628fc8d46387
Create Date: 2026-07-27 18:28:55.312577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd46f554e0dc'
down_revision: Union[str, Sequence[str], None] = '628fc8d46387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bodyweight_entries', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_bodyweight_entries_user_id'), ['user_id', 'date'])

    with op.batch_alter_table('ingredient_items', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ingredient_items_name'), ['name'])

    with op.batch_alter_table('shopping_checks', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_shopping_checks_user_id'), ['user_id', 'week_start', 'ingredient_item_id'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_profiles_user_id'), ['user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_profiles_user_id'), type_='unique')

    with op.batch_alter_table('shopping_checks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_shopping_checks_user_id'), type_='unique')

    with op.batch_alter_table('ingredient_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ingredient_items_name'), type_='unique')

    with op.batch_alter_table('bodyweight_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_bodyweight_entries_user_id'), type_='unique')

    # ### end Alembic commands ###
