"""ingredient nutrition + recipe ownership

Revision ID: d9575c00f9df
Revises: 676a575cbae2
Create Date: 2026-07-27 22:31:16.147472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9575c00f9df'
down_revision: Union[str, Sequence[str], None] = '676a575cbae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kcal_per_100', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('protein_per_100', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('carbs_per_100', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('fat_per_100', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('grams_per_unit', sa.Float(), server_default='1', nullable=False))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_recipes_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_recipes_created_by_user_id_users'), 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_created_by_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_recipes_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('ingredient_items', schema=None) as batch_op:
        batch_op.drop_column('grams_per_unit')
        batch_op.drop_column('fat_per_100')
        batch_op.drop_column('carbs_per_100')
        batch_op.drop_column('protein_per_100')
        batch_op.drop_column('kcal_per_100')

    # ### end Alembic commands ###
